# -*- coding: utf-8 -*-
"""face.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zi_sdahKm_6u41XvW546NaZaqDk7n-as
"""

!pip install face-detection
import cv2
import face_detection
print('Nhập tên tệp ở trong thiết bị của bạn mà bạn muốn nhận dạng (phân biệt chữ thường chữ in hoa, nhập vào định dạng .jpg,.png, VD:face.jpg):')
a=input()
detector = face_detection.build_detector("DSFDDetector", confidence_threshold=.5, nms_iou_threshold=.3) 
img = cv2.imread(a) 
detections = detector.detect(img) 
print(detections)
color = (255, 0, 0)   
thickness = 3
for face in range(len(detections)):
  pts1 = (detections[face][0],detections[face][1])
  pts2 = (detections[face][2],detections[face][3])
  image = cv2.rectangle(img, pts1, pts2, color, thickness) 
print('Chương trình đã nhận dạng xong. Yêu cầu nhập tên tệp để xuất hình ảnh đó ra (không trùng với tên tệp có sẵn, nhập vào định dạng .jpg,.png, VD:detect.jpg):')
a=input();
cv2.imwrite(a, image)